### ISSUE TITLE
Warning: Invalid DOM property `fill-rule`. Did you mean `fillRule`?

### ISSUE THREAD

**Issue by sabreu-teknorix** [ant-design/ant-design-icons#603] opened 2023-09-27 10:04 UTC
I am getting this warning in the console
![image](https://github.com/ant-design/ant-design-icons/assets/88586940/a15045e1-716c-4388-9980-79501b14508e)

**Comment by localpath** [comment] 2023-10-08 03:16
@sabreu-teknorix submitted a PR against this invalid prop

**Comment by linround** [comment] 2023-12-29 07:57
When will it be fixed?

**Comment by vryzhova** [comment] 2024-02-07 12:45
@localpath Will it be fixed in version "@ant-design/icons": "4.0.0"?) And when?)

**Comment by RobbertWolfs** [comment] 2024-02-21 13:29
its also on other icons.. 

<img width="827" alt="image" src="https://github.com/ant-design/ant-design-icons/assets/12511178/c19ecd70-a177-40ff-84d1-bebbc5db0908">

**Comment by afc163** [comment] 2024-02-21 13:35
@RobbertWolfs Could you provide a codesandbox reproduce?

**Comment by localpath** [comment] 2024-02-23 03:37
@afc163 I opened a PR already for this fix. You can see here the SVG is incorrectly implemented not using JSX prop syntax, rather a mix of JSX and HTML syntax

https://github.com/ant-design/ant-design-icons/pull/604/files#diff-0fc7bc4d89c25c35eb2e9992006a736c290c47643fca45f5153c057778986c27

**Comment by afc163** [comment] 2024-02-23 04:30
@localpath Could you provide a codesandbox reproduce?

**Comment by RobbertWolfs** [comment] 2024-02-26 09:07
@afc163  As you can see we just have a basic react + vite setup with ant design installed and when you open the console you see the same issue 

https://codesandbox.io/p/devbox/fervent-minsky-skhhlk

<img width="704" alt="image" src="https://github.com/ant-design/ant-design-icons/assets/12511178/bdb84767-c122-469c-a02c-127f1406cb03">


And as you can see its on multiple icons 

![image](https://github.com/ant-design/ant-design-icons/assets/12511178/273aa173-6b2b-48eb-8e4e-631f9cfbb7a2)

**Comment by sonpm283** [comment] 2024-03-06 09:53
bed like I got this error,
Maybe it's due to a problem with the SVG icon without converting the JSX code
 fill-rule="evenodd" -> fillRule="evenodd"
 clip-rule="evenodd" -> clipRule="evenodd" 

![image](https://github.com/ant-design/ant-design-icons/assets/85411856/708983cd-d0b9-4def-b524-a2faa0222696)

**Comment by diegonc** [comment] 2024-07-30 18:33
I come here to report this issue for icon `ExportOutlined` :confused:  and ping for the status obviously

![image](https://github.com/user-attachments/assets/6f5ca683-c967-47eb-8d5c-f4a9d6f6a641)

**Closed as completed** 2024-09-15 15:31 UTC
